sys:
    libxml2: null
    libxml2-dev: null
    libxslt1.1: null
    libxslt1-dev: null
    postgresql-client: null
    libpq-dev: null
    libffi-dev: null
    libpoppler-cpp-dev: null
    libtiff-dev: null
pip:
    airbrake: "2.1.0"
    amqp: "1.4.9"
    azure: "1.0.3"
    billiard: "3.5.0.3"
    boto: "2.43.0"
    boto3: "1.7.0"
    celery: "4.0.2"
    kombu: "4.0.2"
    certifi: "0.0.8"
    coverage: "4.0.1"
    croniter: "0.3.4"
    cython: "0.25.2"
    cytoolz: "0.8.2"
    ddt: "1.1.1"
    Delorean: "0.4.3"
    Django: "1.11.12"
    django-braces: "1.12.0"
    django-brutebuster: "0.1.8"
    git+https://github.com/celery/django-celery-beat.git@0073f403a68b20bc7478e4bb9fb855d768e041d5#egg=django-celery-beat: null
    django-cors-headers: "2.1.0"
    django-debug-toolbar: "1.9.1"
    django-extensions: "1.9.6"
    django-filter: "1.1.0"
    django-formtools: "2.1.0"
    django-jenkins: "0.110.0"
    django-mama-cas: "2.3.0"
    django-otp: "0.4.1.1"
    django-otp-yubikey: "0.4.2"
   # django-pgcli: "0.0.3"
   # django-pgjson: "0.3.1"
    django-qsstats-magic: "1.0.0"
    django-redis: "4.8.0"
    python-redis-lock[django]: "3.2.0"
    django-sslserver: "0.20"
    django-storages: "1.6.5"
    django-transaction-hooks: "0.2"
    django-two-factor-auth: "1.6.2"
    git+https://github.com/jazzband/django-widget-tweaks.git@35822bf5bd29fa8ec9976993b9a3bf9b5241c8d6#egg=django-widget-tweaks: "1.4.1"
    djangorestframework: "3.7.7"
    drf-yasg: "1.10.1"
    coreapi: "2.3.3"
    git+https://github.com/eofs/django-rest-framework-proxy.git@1fa51b14df364e3dfca3afe57179efefc184d64f#egg=django-rest-framework-proxy: "1.6.0"
    git+https://github.com/Hipo/drf-extra-fields.git@da542863330d69bbce2e7369f03a3d7674893a7a#egg=django-extra-fields: null
    django-polymorphic: "1.3"
    git+https://github.com/chibisov/drf-extensions.git@ce38f21805814a541c3a11c35aa7c0e0eabc237e#egg=drf-extensions: "0.3.2"
    dropbox: "2.2.0"
    enum34: "1.1.6"
    eventlet: "0.18.4"
    factory_boy: "2.8.1"
    fakeredis: "0.8.1"
    freezegun: "0.3.8"
    futures: "3.2.0"
    fuzzywuzzy: "0.2"
    gdata: "2.0.18"
    gevent: "1.1.0"
    #git+https://github.com/Captricity/airbrake-django.git@0b4f1910ebfa7aef3f981f07af8874859cc119b6#egg=airbrake-django: null
    #git+https://github.com/Captricity/captools.git#egg=captools: null
    #git+https://github.com/Captricity/django-dynamicresponse.git@f57e6794818fd6e0c49a4c11e79fa1c412dd3b5d#egg=django-dynamicresponse: "0.6.0"
    #git+https://github.com/Xof/django-pglocks.git@25c4e8e5beb3a53bafd3b91e55a3de07dba2812e#egg=django-pglocks: null
    #git+https://github.com/woohp/pdfrender@0.2.4: null
    #git+https://github.com/woohp/tiffrender@0.1: null
    oauth2client: "4.1.2"
    google-api-python-client: "1.6.4"
    graphene: "1.1.3"
    graphene-django: "1.3"
    graphql-core: "1.1"
    graphql-relay: "0.4.5"
    gunicorn: "19.6.0"
    httpretty: "0.8.8"
    #h5py: "2.7.0"
    inquirer: "2.1.6"
    ipaddr: "2.1.10"
    iso8601: "0.1.11"
    jsonpickle: "0.9.6"
    jsonschema: "2.6.0"
    jinja2: "2.8.1"
   # Keras: "2.1.3"
    keystoneauth1: "2.19.0"
    kombu-redis-priority: "0.3.0"
    lxml: "3.4.4"
    mailchimp3: "3.0.6"
    mandrill: "1.0.57"
    #matplotlib: "1.4.0"
    mechanize: "0.2.5"
    meta: "0.4.1"
    mock: "2.0.0"
    mocurly: "0.2.3"
    moto: "1.3.4"
    mox: "0.5.3"
    numpy: "1.10.4"
    pgcli: "1.5.1"
    pillow: "5.3.0"
    progress: "1.2"
    psycopg2: "2.8.3"
    pyenchant: "1.6.6"
    #pygraphviz: "1.2"
    pylibmc: "1.3.0"
    python-Levenshtein: "0.11.2"
    python-keystoneclient: "3.10.0"
    python-daemon: "1.6.1"
    python-dateutil: "2.4.0"
    python-memcached: "1.53"
    python-statsd: "1.6.3"
    python-swiftclient: "3.3.0"
    pytz: "2014.4"
    radon: "1.4.2"
    recurly: "2.2.23"
    redis: "2.10.5"
    requests: "2.11.1"
    #scikit-image: "0.11.3"
    #scikit-learn: "0.17.1"
    six: "1.10.0"
    slumber: "0.7.0"
    tabulate: "0.7.5"
    tensorflow: "1.8.0"
    termcolor: "1.1.0"
    testfixtures: "4.3.2"
    #theano: "0.8.2"
    #https://download.pytorch.org/whl/cpu/torch-1.0.0-cp27-cp27mu-linux_x86_64.whl: null
    virtualenv: "1.11.6"
    wal-e: "0.8.1"
    watchdog: "0.7.1"
    xlrd: "0.7.1"
    xlutils: "1.3.2"
    xlwt: "0.7.2"
    zstandard: "0.8.1"
yarn: 
    bootstrap-sass: "^3.3.7"
    "@angular/animations": "5.2.4"
    "@angular/common": "5.2.4"
    "@angular/compiler": "5.2.4"
    "@angular/core": "5.2.4"
    "@angular/forms": "5.2.4"
    "@angular/http": "5.2.4"
    "@angular/platform-browser": "5.2.4"
    "@angular/platform-browser-dynamic": "5.2.4"
    "@angular/router": "5.2.4"
    "@types/pdfjs-dist": "0.1.1"
    core-js: "2.4.1"
    ng2-datepicker: "2.1.3"
    ng2-file-upload: "1.3.0"
    ngx-cookie-service: "2.2.0"
    pdfjs-dist: "1.9.489"
    rxjs: "5.5.6"
    zone.js: "0.8.19"
    gulp: "3.9.1"
    gulp-autoprefixer: "6.0.0"
    gulp-header: "1.8.8"
    gulp-if: "2.0.2"
    gulp-concat: "2.6.1"
    gulp-coffee: "2.3.3"
    gulp-uglify: "2.0.0"
    gulp-sass: "3.0.0"
    gulp-clean-css: "2.3.2"
    gulp-angular-templatecache: "1.8.0"
    gulp-ng-annotate: "2.0.0"
    gulp-util: "3.0.8"
    gulp-gzip: "1.4.0"
    gulp-pug: "3.2.0"
    gulp-plumber: "1.1.0"
    gulp-sourcemaps: "2.3.0"
    del: "2.2.2"
    run-sequence: "1.2.2"
    bower: "1.8.0"
    "@types/node": "6.0.60"    
    "@angular/cli": "1.7.3"
    "@angular/compiler-cli": "5.2.4"
    "@angular/language-service": "5.2.4"
    "@types/jasmine": "2.8.3"
    "@types/jasminewd2": "2.0.2"
    "@types/node": "6.0.60"
    "@types/pdf": "0.0.31"
    codelyzer: "4.0.1"
    is-docker: "1.1.0"
    jasmine-core: "2.8.0"
    jasmine-spec-reporter: "4.2.1"
    karma: "2.0.0"
    karma-chrome-launcher: "2.2.0"
    karma-coverage-istanbul-reporter: "1.2.1"
    karma-jasmine: "1.1.0"
    karma-jasmine-html-reporter: "0.2.2"
    karma-jasmine-jquery: "0.1.1"
    karma-phantomjs-launcher: "1.0.2"
    karma-junit-reporter: "1.2.0"
    protractor: "5.1.2"
    ts-node: "4.1.0"
    tslint: "5.9.1"
    typescript: "2.5.3"
    concurrently: "^3.1.0"
    phantomjs-prebuilt: "2.1.14"
bower: 
    jquery: "2.2.1"
    jquery.cookie: "~1.4.1"
    lodash: "4.14.1"
    angular: "1.5.11"
    angular-animate: "1.5.11"
    angular-cookies: "1.5.11"
    angular-ui-router: "0.3.2"
    angular-strap: "2.3.8"
    restangular: "1.5.2"
    bootstrap-sass-official: "3.3.6"
    bootstrap: "3.3.6"
    moment: "2.12.0"
    #angular-moment: "0.10.3"
    amitava82-angular-multiselect: "bac4ab42f3255233c84de06722df88fbfb1fdc35"
    bootstrap-daterangepicker: "1.3.18"
    angular-sanitize: "1.5.11"
    angular-mocks: "1.5.11"
    fontawesome: "4.6.3"