#!/usr/bin/env python

from __future__ import absolute_import

import os
import click
import json
import six
import collections
import subprocess
import yaml
from distutils.spawn import find_executable

from cappa.factory import manager_key_to_cappa, private_manager_key_to_cappa
from cappa.enums import ALL_MANAGERS


@click.group()
def cappa():
    pass


@click.command()
@click.option('--requirements', '-r', default=None, type=click.File('r'),
              help='install using requirements json/yaml file')
@click.option('--warn', is_flag=True,
              help='print errors as warning and continue')
@click.option('--private-https-oauth', is_flag=True,
              help='Use oauth authenticated https for private repositories (requires GITHUB_TOKEN env var)')
@click.option('--use-venv/--no-venv', default=True,
              help='Assumes install uses a python virtualenv')
@click.option('--ignore', default='',
              help='Comma separated list of managers to ignore')
@click.option('--only', default='',
              help='Comma separated list of managers to install')
@click.option('--save-js/--no-save-js', default=False,
              help='Save generated json files for npm/bower/typings/tsd installs')
def install(requirements,
            warn,
            private_https_oauth,
            use_venv,
            ignore,
            only,
            save_js):
    if ignore and only:
        raise click.ClickException('Only one of ignore-managers and install-only can be set')

    if only:
        only = only.split(',')
        ignore = filter(lambda manager: manager not in only, ALL_MANAGERS)
    else:
        ignore = ignore.split(',')

    requirements_dir = os.path.dirname(requirements.name)
    if requirements_dir:
        os.chdir(requirements_dir)

    if requirements.name.endswith('.json'):
        requirements = json.load(requirements, object_pairs_hook=collections.OrderedDict)
    elif requirements.name.endswith('.yaml'):
        # this is a convoluted way to use an OrderedDict as the primary dictionary
        # https://stackoverflow.com/questions/5121931/in-python-how-can-you-load-yaml-mappings-as-ordereddicts
        class OrderedLoader(yaml.Loader):
            pass

        def construct_mapping(loader, node):
            loader.flatten_mapping(node)
            return collections.OrderedDict(loader.construct_pairs(node))
        OrderedLoader.add_constructor(yaml.resolver.BaseResolver.DEFAULT_MAPPING_TAG, construct_mapping)
        requirements = yaml.load(requirements, OrderedLoader)

    for key, packages in six.iteritems(requirements):
        if key in ignore:
            continue
        if key == 'Captricity':
            for private_key, private_packages in six.iteritems(packages):
                CappaClass = private_manager_key_to_cappa(private_key)
                pa = CappaClass(key, warn, private_https_oauth, use_venv, save_js)
                pa.install(private_packages)
        else:
            CappaClass = manager_key_to_cappa(key)
            pa = CappaClass(warn, private_https_oauth, use_venv, save_js)
            pa.install(packages)
cappa.add_command(install)


@click.command(name='list')
def list_all():
    """List installed packages"""
    if find_executable('bower'):
        click.echo('bower')
        # bower -o (offline) option prevents checking for updates when listing packages
        subprocess.call(['bower', 'list', '-o'])
    if find_executable('npm'):
        # npm --depth=0 lists top level packages without listing all sub-dependencies
        npm_args = ['npm', 'ls', '--depth=0']
        # npm -g option to list global packages
        npmg_args = npm_args + ['-g']
        click.echo('npm')
        subprocess.call(npm_args)
        click.echo('npmg')
        subprocess.call(npmg_args)
    if find_executable('pip'):
        click.echo('pip')
        subprocess.call(['pip', 'list'])
    if find_executable('dpkg'):
        click.echo('system')
        subprocess.call(['dpkg', '-l'])
cappa.add_command(list_all)


@click.command()
def remove():
    click.echo('remove')
cappa.add_command(remove)


@click.command()
def version():
    click.echo('0.16.1')
cappa.add_command(version)

if __name__ == '__main__':
    cappa()
