#!/usr/bin/env python

import click
import json
import collections

from cappa import CapPA

@click.group()
def cappa():
    pass

@click.command()
@click.option('--requirements', '-r', default=None, type=click.File('rb'),
              help='install using requirements json file')
@click.option('--warn', is_flag=True,
              help='print errors as warning and continue')
@click.option('--private-https-oauth', is_flag=True,
              help='Use oauth authenticated https for private repositories (requires GITHUB_TOKEN env var)')
@click.argument('packages', nargs=-1)
def install(requirements, warn, private_https_oauth, packages):
    pa = CapPA(warn, private_https_oauth)
    if requirements is None:
        pa.install(packages)
    else:
        pa.install(json.loads(requirements.read(), object_pairs_hook=collections.OrderedDict))
cappa.add_command(install)

@click.command()
def list():
    click.echo('list')
cappa.add_command(list)

@click.command()
def remove():
    click.echo('remove')
cappa.add_command(remove)

if __name__ == '__main__':
    cappa()
